FROM node:18-bullseye AS build

WORKDIR /app

COPY web/package.json frontend/pnpm-lock.yaml ./
RUN pnpm i

COPY web/ ./
RUN pnpm run build

FROM node:18-alpine AS run

WORKDIR /app

COPY --from=build /app/package.json /app/pnpm.yaml ./
RUN pnpm install --no-optional --prod --ignore-scripts
RUN pnpm audit --fix --prod --no-optional

COPY --from=build /app/.svelte-kit/output/ ./
EXPOSE 3000
CMD ["node", "./index.js"]