FROM golang:1.19-bullseye AS build

WORKDIR /app

COPY go.mod go.sum dicetrace.go ./
COPY apps/api/internal ./internal

RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -a -o dicetrace .

FROM alpine:3.17 AS run

COPY --from=build /app/dicetrace .

ENTRYPOINT ["./dicetrace"]
